### ISSUE TITLE
Add "Back" button on single asset view

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1064]
**Is your feature request related to a problem? Please describe.**
This is just a feature request as I think it might improve navigation.

**Describe the solution you'd like**
I believe we need a "Back" button on the asset view. I know we can go back to homepage by clicking on the menu logo, but I think we can improve the navigation experience by adding a "Back" button.

For example:

![Item](https://user-images.githubusercontent.com/13741335/152802801-e6863348-0ca6-4fbd-908e-0970c1975df2.png)

**Comment by kremalicious** [comment]
this assumes people get to asset details only from the homepage but there are many other ways they end up on asset details view, so that button is not so clear then. As we don't have any nested page flows I would say any sort of back button for browser-native functionality (actual back button, swipe from left on mobile) would be more noise than bringing usefulness

**Comment by EnzoVezzaro** [comment]
yeah, this might be true. I definitely find it uncomfortable having to go to the top left corner of my screen just to "go back" (mostly going home), but it might also be due to my screen which is actually big (iMac 27"). But it's something we can pospone for sure.

**Comment by mihaisc** [comment]
Is this still relevant? I think we can close it

**Comment by EnzoVezzaro** [comment]
> Is this still relevant? I think we can close it

Yes, agree. We can close it for now.
