### ISSUE TITLE
Multi-chain test

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1117]
Test for the following chains ; 
- rinkeby
- mumbai
- ropsten
- moonbase

For each :
- publish an asset with all each of the pricing schema
- ordering
- add/remove liquidity
- profile page should be displaying relevant information (except compute jobs and pool shares)
- search/filter/sort

As an output, for any issue discovered during testing, open the item on the specific repository

Also please comment here the address of your wallet, we need to get some info regarding gas cost/estimates for v4.

**Comment by AnaLoznianu** [comment]
Hey @moritzkirstein I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/frontend-60acd67b133a660014278212/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by LucaMilanese90** [comment]
Account used for testing: [0xbEe7E78668fd81d02D33Fc41aAD70AAa815B0916]
(https://rinkeby.etherscan.io/address/0xbee7e78668fd81d02d33fc41aad70aaa815b0916)

Rinkeby:
- [ ] Publish asset with each pricing schema
    - Fixed: [did:op:10c534fb3af661cf879f19d84e95c683dee6409bbb1f2a8ec8cb4cdfd3a21e9d](https://market-git-v4-oceanprotocol.vercel.app/asset/did:op:10c534fb3af661cf879f19d84e95c683dee6409bbb1f2a8ec8cb4cdfd3a21e9d)
    - Pool: [did:op:99fd9981a1b6b0cdff2c88622ffd8a16c6f41952e8bcd62c786f97dc33fc0aee](https://market-git-v4-oceanprotocol.vercel.app/asset/did:op:99fd9981a1b6b0cdff2c88622ffd8a16c6f41952e8bcd62c786f97dc33fc0aee)
    - Free: [did:op:f9e604ec146b1a8fff28afbdd76d0cd46a36ce4af34eee02be01121891ef69fe](https://market-git-v4-oceanprotocol.vercel.app/asset/did:op:f9e604ec146b1a8fff28afbdd76d0cd46a36ce4af34eee02be01121891ef69fe)
    
- [ ] Ordering
Failed orders : it was not possible to order assets with free price due to an error thrown when trying to access the asset details page.
Successfully ordered assets: 
    - Fixed [did:op:e944bc6dedb470e574bb5c1fe9d938ddcb433d02cc7bb723d5ee7a41eeb0c17e](https://market-git-v4-oceanprotocol.vercel.app/asset/did:op:e944bc6dedb470e574bb5c1fe9d938ddcb433d02cc7bb723d5ee7a41eeb0c17e)
    - Pool [did:op:99fd9981a1b6b0cdff2c88622ffd8a16c6f41952e8bcd62c786f97dc33fc0aee](https://market-git-v4-oceanprotocol.vercel.app/asset/did:op:99fd9981a1b6b0cdff2c88622ffd8a16c6f41952e8bcd62c786f97dc33fc0aee)

- [ ] Add & remove liquidity: not working, clicking on "add liquidity" throws an error 
- [ ] Profile page displays relevant information
- [ ] Search
- [ ] Filter
- [ ] Sort

Moonbase:
- [ ] Publish asset with each pricing schema
    - Fixed: []()
    - Pool: []()
    - Free: []()
    
- [ ] Ordering
Failed orders : it was not possible to order assets with free price due to an error thrown when trying to access the asset details page.
Successfully ordered assets: 
    - Fixed []()
    - Pool []()

- [ ] Add & remove liquidity: not working, clicking on "add liquidity" throws an error 
- [ ] Profile page displays relevant information
- [ ] Search
- [ ] Filter
- [ ] Sort

Ropsten:
- [ ] Publish asset with each pricing schema
    - Fixed: []()
    - Pool: []()
    - Free: []()
    
- [ ] Ordering
Failed orders : it was not possible to order assets with free price due to an error thrown when trying to access the asset details page.
Successfully ordered assets: 
    - Fixed []()
    - Pool []()

- [ ] Add & remove liquidity: not working, clicking on "add liquidity" throws an error 
- [ ] Profile page displays relevant information
- [ ] Search
- [ ] Filter
- [ ] Sort

Mumbai:
- [ ] Publish asset with each pricing schema
    - Fixed: []()
    - Pool: []()
    - Free: []()
    
- [ ] Ordering
Failed orders : it was not possible to order assets with free price due to an error thrown when trying to access the asset details page.
Successfully ordered assets: 
    - Fixed []()
    - Pool []()

- [ ] Add & remove liquidity: not working, clicking on "add liquidity" throws an error 
- [ ] Profile page displays relevant information
- [ ] Search
- [ ] Filter
- [ ] Sort

**Comment by LucaMilanese90** [comment]
Just opened a few issues with the problems I encountered during my testing: 
#1154
#1155
#1156
#1157
#1158
#1159
#1160
#1161
#1162
#1163
#1164
#1165

**Comment by kremalicious** [comment]
considering this ongoing and we're all busy opening new issues (thanks everyone!) so no need to specifically track this here
