### ISSUE TITLE
Think of a way to handle slow network

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1118]
On rinkeby we are getting pretty often the following `Transaction was not mined within 50 blocks, please make sure your transaction was properly sent... ` . This is because the network is slow .  What can we do to improve the experience?

**Comment by EnzoVezzaro** [comment]
I'm my opinion it'd be much better if we could show a "Pending Transaction" (button / alert) instead of just restoring the UI. It's very confusing when this happens. I think that showing a "Pending Transaction" somewhere (with an alert or on the buttons themselves) to notify the user that there's a pending transaction and he is basically "Stuck" for a bit could be already a better user experience. Because when this happens, the user is tempted to retry (queuing more transactions) because he's never gotten any feedback. But if we show something, at least the user will know there's being a problem and he must wait a bit. I've seen this in other dApps. This doesn't solve the initial problem, but it might be a little improvement.

**Comment by mihaisc** [comment]
This could work for all actions except publish where you have 2 chained tx.

**Comment by EnzoVezzaro** [comment]
> This could work for all actions except publish where you have 2 chained tx.

Yeah, exactly. Unfortunately, the publish flow requires another solutions even thought with this we would notify the user there's something going on, at least the user has the change to see what's happening and he can decide if retry (causing more tx to get queued) or wait until the one pending is done.

**Comment by kremalicious** [comment]
We need to figure out where this "Transaction was not mined within 50 blocks" threshold is coming from, and then as a start increase this so we simply wait longer for tx to finish

**Comment by mihaisc** [comment]
we can do that in ocean.js config. The main thing we need to to is to check if the ocean.js config regarding gas is actually working. Also at the end of the day if the network is busted what can you do?

**Comment by kremalicious** [comment]
> Also at the end of the day if the network is busted what can you do?

yeah exactly. So just more transparency would be sufficient solution too, meaning somehow detecting slow network, then on asset detail screen put prominent warning at very top that network is slow or congested and things might fail. Not sure we find a reliable check which does not trigger this warning all the time.

**Comment by mihaisc** [comment]
no concrete action for this
