### ISSUE TITLE
Pool tab not updating when changing account

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1152]
When you are in add/remove liquidity screen and you change your account the values don't update. When you go back to main pool tab  the data is still from the old account.
Also, because of this, when you remove all your liquidity you can still see the Remove button

**Comment by AnaLoznianu** [comment]
Check if this isn't already fixed with the latest merged PRs

**Comment by kremalicious** [comment]
checked with current `v4` branch, problem is the interval fetching. Numbers update correctly on add/remove liquidity upon account change, and also in front of Pool tab. But the interval kicking in leads to fetching with former `accountId` and the old numbers are back.

Instead of hacking around with trying to clear interval and maybe split up user pool info and general pool info again, we might wanna check out `urql` and how its architecture could have a replacement for simple interval re-fetching which in turn would then remove this bug here.

Like:
- https://formidable.com/open-source/urql/docs/advanced/retry-operations/
- https://formidable.com/open-source/urql/docs/basics/ui-patterns/#reacting-to-focus-and-stale-time
