### ISSUE TITLE
Pool transaction tab in profile shows incorrect infos

### ISSUE THREAD

**Issue by LucaMilanese90** [oceanprotocol/market#1157]
**Describe the bug**
In the pool transaction tab in the profile section only title (but the link it points to is broken) and time seem to be correct, data set field is empty, network is always unknown.

**Screenshots**
![Screenshot 2022-03-03 at 16 04 29](https://user-images.githubusercontent.com/20192135/156609145-a975bc4d-ad02-4fe5-a0cd-146864783959.png)

**Comment by kremalicious** [comment]
Should be fixed with #1139 although I get now a mix of assets with info and without. But might be because of older test assets interacted with my account but something to look out for when verifying if bug is gone

on https://market-git-feature-issue1042-restore-pool-section-oceanprotocol.vercel.app/profile

<img width="1135" alt="Screen Shot 2022-03-09 at 12 31 08" src="https://user-images.githubusercontent.com/90316/157442288-47d2a4e7-9825-4fe4-922a-cbdb4c72d999.png">
