### ISSUE TITLE
Edit UI

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1244]
It works, but it could be better. Biggest issues to solve:

- mix of form elements where some are prefilled and some are not making it hard to know which fields will be edited or cleared
- How to clear fields
- ...

**Comment by EnzoVezzaro** [comment]
> * mix of form elements where some are prefilled and some are not making it hard to know which fields will be edited or cleared

Here the difficulty is getting the File and Sample file url. What we can do is placing a "placeholder" like this: 

![Screenshot 2022-08-09 at 10 08 02](https://user-images.githubusercontent.com/13741335/183671536-bd980a78-a9a3-4d1e-89e5-4b4e06cc96ed.png)

if the user clicks on "Download" then we start a tx to download the file or sample file (after the download we should display it correctly). 

![Screenshot 2022-08-09 at 10 07 48](https://user-images.githubusercontent.com/13741335/183671883-fc2aafcc-e190-47b9-9378-d93ea06b23fa.png)

Otherwise the user can remove the placeholder with the "x" to add another link. 

> * Remove/Hide tabs during editing

If we remove the tabs, we won't be able to access the "EDIT COMPUTE SETTINGS":
![Screenshot 2022-08-09 at 10 00 37](https://user-images.githubusercontent.com/13741335/183668815-7c979e6c-9fd2-4257-924d-5214f8a0fb66.png)

> * How to clear fields

Not sure if a clean button like an styled "x" on the single field would do or do you a mean a generic button that clears the whole form? 🤔

**Comment by EnzoVezzaro** [comment]
On the other hand, we can implement an "edit" CTA on each field to let the user know exactly which field he's editing. Any change will trigger a tx to change this specific field. What I proposed is something like this: 

Edit Metadata:
<img width="1001" alt="Screenshot 2022-08-17 at 09 48 54" src="https://user-images.githubusercontent.com/13741335/185150963-89971a0c-1595-4466-a73f-d8805054b846.png">

Compute Settings: 
<img width="996" alt="Screenshot 2022-08-17 at 09 49 00" src="https://user-images.githubusercontent.com/13741335/185151036-a229fabb-ec1a-49ae-abfd-11c73d2955a3.png">

**Comment by EnzoVezzaro** [comment]
> On the other hand, we can implement an "edit" CTA on each field to let the user know exactly which field he's editing. Any change will trigger a tx to change this specific field. What I proposed is something like this:
> 
> Edit Metadata: <img alt="Screenshot 2022-08-17 at 09 48 54" width="1001" src="https://user-images.githubusercontent.com/13741335/185150963-89971a0c-1595-4466-a73f-d8805054b846.png">
> 
> Compute Settings: <img alt="Screenshot 2022-08-17 at 09 49 00" width="996" src="https://user-images.githubusercontent.com/13741335/185151036-a229fabb-ec1a-49ae-abfd-11c73d2955a3.png">
> 
> WIP: still trying to understand what's the best way to clear this fields as there's already a lot of ui elements in the page, I don't want to just add another element to this.

should we start working on this? is this a good UX strategy for our use case or it's too much? Thanks, @AnaLoznianu @kremalicious

**Comment by AnaLoznianu** [comment]
@EnzoVezzaro I think this is a great start, but I suggest the following: 
Edit Metadata: 
Triggering transactions on each field I think is too much.

If I understand the design you propose here, then the user needs to click on the 'Edit' button for a certain field, and then on  'Done' to submit the change. I think having only a 'Submit' button for the entire form is easier. 
What I suggest is, if the user did a change on a field, maybe color that field text with a different color(like our pinky theme). 
Also, I like the proposal for the 'New File' and 'Sample file URL'.
For Clearing the fields, I think we should stay consistent with the URL fields. Having an 'X' on each one.

Edit compute settings: 
Personally, I don't think we need changes here.

**Comment by jamiehewitt15** [comment]
Yeah, I agree with Ana that it's best to avoid over complicating it. I think a good place to start on this would just be to ensure that all the fields are pre-populated. Provider use to have an endpoint (`/assetUrls`) to retrieve the asset URL, I think it has been deprecated though.  @calina-c might be able help to point you in the right direction if there is still a way to get the asset URL

**Comment by EnzoVezzaro** [comment]
> What I suggest is, if the user did a change on a field, maybe color that field text with a different color(like our pinky theme).
> For Clearing the fields, I think we should stay consistent with the URL fields. Having an 'X' on each one.

this is a great idea. I'll mockup with a design shortly.

**Comment by AnaLoznianu** [comment]
Linked issue: https://github.com/oceanprotocol/aquarius/issues/871
We will add validation on fields based on the exposed aqua shacl schema
