### ISSUE TITLE
The publish fails when using  a large string as a description

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1269]
**Describe the bug**
Adding a long string in the asset descriptions leads to the error seen in the below screenshot.

<img width="1278" alt="Screenshot 2022-03-28 at 15 53 41" src="https://user-images.githubusercontent.com/84312885/160402490-4f63195d-c9b4-43aa-af1d-1c0003c11376.png">

Published description text is available here: https://drive.google.com/file/d/12iat8Mt3xKwU3fWW4cJE_0qPd-tW8JlN/view?usp=sharing
Network: Rinkeby
OS: MacOS

**Comment by bogdanfazakas** [comment]
Based on the console errors, saw that decodeUri fails, I have a PR (https://github.com/oceanprotocol/ocean.js/pull/1365) on oceanjs where we remove the decodeUri from the encrypt function since we never use encodeUri on market side, and i can test the market with a local of oceanjs with those changes to see if it also solves this issue

**Comment by bogdanfazakas** [comment]
Tested with a local oceanjs that removes the use of decodeUri that was failing on encrypt (in this oceanjs PR https://github.com/oceanprotocol/ocean.js/pull/1386), and the market error is no longer present, But still the publish is failing with an RPC issue. See RPC error received on setMetadata below 👇
<img width="1876" alt="Screenshot 2022-04-01 at 16 10 52" src="https://user-images.githubusercontent.com/13447142/161270813-ee8776fe-e69c-461c-a137-ec4f44a54f92.png">

**Comment by mihaisc** [comment]
hmm, kinda makes sense i think. @alexcos20 what would be the max?

**Comment by AnaLoznianu** [comment]
Set maximum to 5K characters
