### ISSUE TITLE
Remove/Hide tabs during editing 

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1297]
**Is your feature request related to a problem? Please describe.**
Can we remove or hide these tabs above the updating popup? After pressing edit, I suggest to hide or remove it.

<img width="1440" alt="Screen Shot 2022-04-01 at 5 47 41 AM" src="https://user-images.githubusercontent.com/13741335/161241103-66099907-ee63-4077-be09-4525435051c2.png">

**Comment by kremalicious** [comment]
Yes, the UI of this has just been made work, not actually designed. Which is why #1244 exists and I would suggest using that as a collection issue, as the edit page is simply not that important in the grand scheme of things so we should not have multiple issues around it all just handling the UI of it

**Comment by AnaLoznianu** [comment]
It will be fixed in: https://github.com/oceanprotocol/market/issues/1244
