### ISSUE TITLE
confirmation screen in edit asset is a bit uncomfortable 

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1298]
**Is your feature request related to a problem? Please describe.**
When you try to edit a file (after submitting your changes), the app enters in a "Updating Data Set" state where it ask you to confirm the transaction. If you refused, or it fails, you get kind of stuck in this screen with the only possibility or retry or exit basically. If an user (and knowing why the tx fail or himself has reject it) clicks on retry, I'd expect to re-run the same transaction. It's weird that by clicking on retry, you get sent to edit page again. I think we should have at least another button to go back to edit or even better we leave the edit form below the popup and add a close button to the "Updating Data" popup.

I propose, instead of sending the user to edit when clicked on retry, we could add something like this where the "X" closes the popup so you can edit the file. Instead if you decide to click on retry, it will actually retry to make the same edit call that failed prevoiusly. 

Instead of this
<img width="890" alt="Screen Shot 2022-04-01 at 6 08 59 AM" src="https://user-images.githubusercontent.com/13741335/161244532-b6a32873-a1d2-44fb-9e1a-3d858c12361a.png">

We could think about this:
![Group 6](https://user-images.githubusercontent.com/13741335/161244582-34596294-bad6-438f-b7a2-1483628eab01.png)

This would also solve this #1297

**Comment by kremalicious** [comment]
same here,  hiding the edit form could be avoided completely and just disabled, making this issue here obsolete. Until then, #1244 should have all the UI ideas.

Lots to talk about in the decision between [Modal vs. Page](https://uxplanet.org/modal-vs-page-a-decision-making-framework-34453e911129), in our case it's about consistency as we decided for Page. Either we use a modal for all blockchain interactions, or not. We should not introduce a mix where some actions trigger a modal and some do not.

**Comment by AnaLoznianu** [comment]
Will be fixed in:https://github.com/oceanprotocol/market/issues/1244
