### ISSUE TITLE
Download button refreshes to show buy button 

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#1357]
During the process of purchasing download access to a dataset, the button constantly keeps refreshing to update the price. This continues to happen after all of the transactions have been signed. When the download button refreshes, it shows the "buy" button again which is very confusing for a user who has already bought the dataset. 

## Video

https://user-images.githubusercontent.com/20739535/165107608-3497facf-b13e-4241-b564-966bc60ac6c7.mp4

## To recreate

1. Buy the dataset and complete the transactions
2. After the "Download" button shows wait a few seconds until the next time that it refreshes.
3. You'll now see the "Buy" button is visible instead of the "Download" button

**Comment by kremalicious** [comment]
If there is a simple fix to close issue we should go for it but the underlying issue is the `ButtonBuy` trying to do way too many things at the same time. This is also reflected in CodeClimate where this component show up as 2nd worse file we maintain:

<img width="815" alt="Screen Shot 2022-05-17 at 12 55 53" src="https://user-images.githubusercontent.com/90316/168805368-7a19e5ac-7296-468f-9d4c-1a05619877f0.png">

And if we have to add that many props to a component although we mostly try to use hooks, then it's clear something is wrong:

<img width="606" alt="Screen Shot 2022-05-17 at 12 58 04" src="https://user-images.githubusercontent.com/90316/168805702-07b157d5-1d1f-467a-ba70-21a63a9daed3.png">

So if we ant to solve this properly and prevent possible further bugs, this component needs to be split up based on our current usage, e.g. dedicated order button & download button components to split the complexity and such
