### ISSUE TITLE
Loader in "Your compute job" doesn't finish loading (Compute/Algorithm)

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1373]
**Describe the bug**
On algoriths/computes: when you press "Your compute job" dropdown, the loader stays up forever. It's working in assets.

**To Reproduce**
1. Go to Algorith
2. Click on "Your compute job" dropdown
3. See loader

Examples:
- https://market-45a115657-oceanprotocol.vercel.app/asset/did:op:b4260f5beefdc226a7c6cd62ef03f387c053e9059bf864c6e625fb44d7d4b813
- https://market-45a115657-oceanprotocol.vercel.app/asset/did:op:ea0ca37da30bd1518f5f014bb6472efa12357cb41e861706a8f822a7e15e323d
- https://market-45a115657-oceanprotocol.vercel.app/asset/did:op:3979313203a1293b6d1c7260883561d6e35ae936ed95dd4a0e60c1f14cb5f677

**Expected behavior**
If there's no results, it should say: No results found

**Screenshots**
<img width="1439" alt="Screen Shot 2022-04-29 at 6 51 49 AM" src="https://user-images.githubusercontent.com/13741335/165931831-d760314a-fea9-491e-8f8a-23700c56508b.png">

**Comment by bogdanfazakas** [comment]
This seems to be a C2D issue and it's better to be tracked on **Restore compute functionality** PR #1069 . The infinite loading was fixed in that PR but not sure if we need to have `Your compute jobs `section on the algorithms detail page or only on datasets.
So I tend closing this and following up with this on the mentioned PR
