### ISSUE TITLE
Error message placement in relation to form fields

### ISSUE THREAD

**Issue by claudiaHash** [oceanprotocol/market#1387]
We should find a universal way to place all the validation error messages in the right places on form fields, throughout the application:

![Screenshot from 2022-05-04 13-40-41](https://user-images.githubusercontent.com/49017601/166667315-be43e845-45e1-4ee8-b22b-35fc44824768.png) ![Screenshot from 2022-05-04 13-40-51](https://user-images.githubusercontent.com/49017601/166667365-94cd06ec-9cf7-4da5-9100-695d2493a62b.png)

**Comment by mihaisc** [comment]
Image 2 is correct, in trade it's a bug

**Comment by claudiaHash** [comment]
Yes, was more for comparison. Not quite a trade bug because the trade, publish and edit inputs rely on the same style css file, so the solution needs to be a generic one, which fixes the trade without affecting the other forms

**Comment by kremalicious** [comment]
the solution was mentioned here https://github.com/oceanprotocol/market/pull/1334#discussion_r854522263

**Comment by mihaisc** [comment]
Soo...we don't really have a solution yet, not a simple one at least. Or did i misunderstand?

**Comment by claudiaHash** [comment]
> Soo...we don't really have a solution yet, not a simple one at least

Yes, exactly. It's more than a quick change in a css file

**Comment by kremalicious** [comment]
yup, we only have a direction, no full solution. From pragmatic standpoint, if we only have this problem on trade tab alone, might be worth having a style overwrite fix only for fields on trade tab.

Otherwise we would need to explore with some isolated test cases, Storybook would be perfect for that, where we can have one story with multiple fields on it with varying text lengths

**Comment by mihaisc** [comment]
Based on previous comments not sure we can have a generic solution
