### ISSUE TITLE
Changing the timeout of an asset doesn't update the action the user can perform: Buy/Download

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1520]
**To Reproduce**
1. Publish an asset with the 'Forever' timeout
2. Buy a datatoken to consume it 
3. Download the asset - It works
4. Go to edit the metadata and change the timeout to 1 day
5. Wait 1 day
6. After 1 day, the asset action is still 'download' but tapping on that gives the error from the screenshot. It should be 'Buy'

<img width="1280" alt="Screenshot 2022-06-15 at 16 32 05" src="https://user-images.githubusercontent.com/84312885/173850565-82b1400e-8d23-4558-b4bb-4dc2c2b21081.png">

**Comment by mihaisc** [comment]
This is a more complex issue that in part was already solved here https://github.com/oceanprotocol/market/pull/1518. We were updating the ddo with some data that we used only in the market. Due to faulty state management in that component the data that we were actually calculating (that was correct) was getting mixed with old data that was written in the ddo (that shouldn't have been there). 
To properly fix this we need considerable refactoring.
