### ISSUE TITLE
Provider only allows 2 min between starting and ending compute order

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1543]
Which is why an error like this is produced when 5 or 6 transactions are not finished within this timeframe:

<img width="1139" alt="Screen Shot 2022-06-23 at 12 58 06" src="https://user-images.githubusercontent.com/90316/175341359-06662647-6593-4a3d-9817-904df21267b8.png">

Issue is just for tracking this as known issue, most likely fix will have to be done on provider only.

**Comment by mihaisc** [comment]
https://github.com/oceanprotocol/provider/issues/498

**Comment by AnaLoznianu** [comment]
@bogdanfazakas Is this still an issue? I remember the 'validUntil' fix was done on Provider

**Comment by bogdanfazakas** [comment]
No, the issue was fixed with some changes to provider that are taking the tx time and the c2d duration we specify into account for computing the time till when the resources are payed, and also with the market update that changed the order in which the assets are ordered,  and the last tx will be the asset with provider fees associated
