### ISSUE TITLE
Mobile user experience for header is bad on small viewports

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#1544]
Trying to press on the profile icon on mobile is an absolute nightmare, I feel like I'm playing a game. I realise that it's not like this on every device so I think we also need to do more testing on other mobile devices - probably we'll find other strange user experiences. 

https://user-images.githubusercontent.com/20739535/175502810-635b3216-7774-47ab-af33-26a5864fa9fb.mp4

Using:
Samsung Galaxy S20 FE
Android 12

**Comment by jamiehewitt15** [comment]
Also, the text is cut of on the profile page. It's impossible to read what the tabs are

![Screenshot_20220624-121648_MetaMask.jpg](https://user-images.githubusercontent.com/20739535/175504978-a329ebb9-5d3d-4e57-8b19-b4808dac824b.jpg)

**Comment by jamiehewitt15** [comment]
Info icon that sits on the nft image is partially off screen 

![Screenshot_20220624-122158_MetaMask.jpg](https://user-images.githubusercontent.com/20739535/175506085-64b79d14-56d6-4035-95fd-932eb2cfe8ed.jpg)

**Comment by jamiehewitt15** [comment]
The padding around the tab titles disappears when the trade tab is selected. This makes the content of that tab much higher 

https://user-images.githubusercontent.com/20739535/175506617-b0f3785d-adb7-4f6c-9756-ecb815c73079.mp4

**Comment by jamiehewitt15** [comment]
@AnaLoznianu should I create separate issues for each of these?

**Comment by AnaLoznianu** [comment]
No, I think we can tackle these minor issues in one issue.

**Comment by kremalicious** [comment]
> Trying to press on the profile icon on mobile is an absolute nightmare

on YOUR mobile. And in the MetaMask browser no less, which is notorious for using outdated rendering engines. Regardless, header layout was tested down to iPhone 5 viewport size, it just happens that your mobile device of 2 years is using a more narrow resolution width than a 10 year old iPhone and on top of that it seems that when we added that version dropdown we also destroyed this header layout on very narrow viewports. 

So 2 options:

- try to squeeze slightly more space out of all the header elements so that on a 1080px viewport width all fits beside each other
- refactor whole header again to have a truly fluid layout so we don't care about any viewport sizes

> if I click on the logo to go back to the home page it turns pink and just stays pink. Never changes back to white

click on anything else on the screen and the hover style of the logo will disappear. Just like on every website accessed via touch and which has any hover styles. Alternative would be:

- remove hover style of logo being pink for everybody
- prevent hover events from firing on touch devices (really bad idea as it requires us to remove all UI elements which are triggered on hover)

All in all, common issue on all touch devices where hover & active events can't be distinguished for both, mobile and desktop viewports. Uniswap has same behavior on their app logo, which gets tilted on hover, but then on touch devices when tapping, it doesn't get tilted back unless something else is tapped on screen.

**Comment by jamiehewitt15** [comment]
> on YOUR mobile

As I said above, I realise that it's not like this on every device but I'm not the only person with phone that has a screen ratio of 20:9. That's the same as iPhone 12 Pro Max, Samsung Galaxy S21 Ultra, OnePlus 9 Pro and many others.

**Comment by mihaisc** [comment]
We can just hide the v4 dropdown part on mobile , not that relevant.

**Comment by jamiehewitt15** [comment]
> We can just hide the v4 dropdown part on mobile, not that relevant.

Yeah that would be a nice simple solution

**Comment by kremalicious** [comment]
> phone that has a screen ratio of 20:9. That's the same as iPhone 12 Pro Max, Samsung Galaxy S21 Ultra, OnePlus 9 Pro and many others.

but that is not the problem, the relationship between screen resolution (...px) and pixel resolution (@2x, @3x..., dpi) is. Here's screenshot on iPhone 11 Pro and there is no layout problem on even bigger iPhones or those other Android devices you mentioned. On those you would see even more of the content and have even more space between the header elements:

![IMG_3736](https://user-images.githubusercontent.com/90316/175545015-6b0c15f5-9071-4450-a234-5dfa41fbdf18.PNG)

Emulated on desktop, I get this for iPhone 13 Pro Max:

<img width="413" alt="Screen Shot 2022-06-24 at 14 21 16" src="https://user-images.githubusercontent.com/90316/175546232-ab169346-1bef-490e-ab2b-49277ff503a1.png">

And this for Galaxy S20 Ultra:

<img width="410" alt="Screen Shot 2022-06-24 at 14 32 03" src="https://user-images.githubusercontent.com/90316/175546364-c73de154-6d37-4086-bc81-f3e4cba34802.png">


I agree that a proper UI should just not care about any of this or a specific device and just be fluid and break layout at comfortable break points depending on content readability. But that current header has a lot of compromises included so we are not forced to move things out of screen or stack into multiple layers moving the main content further down. And all those compromises just don't produce such widespread weird layouts as you encountered.

So would also opt for some quick fix, cause otherwise we would spend ages on that new header.

**Comment by mihaisc** [comment]
Agree with removing version and test. Refactoring is way too time consuming

**Comment by kremalicious** [comment]
Renamed issue title to reflect what has been discussed in here and how it can be closed. Everything in here is either addressed in #1495 or #1549
