### ISSUE TITLE
Potential Impermanent Loss occurrence in V4

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/market#1574]
**Describe the bug**
A user DMed me in Discord today claiming he experienced Impermanent Loss in a V4 Data Set. 

**Expected behavior**
No impermanent loss, or better protection.

**Additional context**
User Wallet Address (Polygon):
0xcF8A4B99640dEfaf99Acae9d770dEC9DfF37927d

Data Set:
https://market.oceanprotocol.com/asset/did:op:c2874ded256d80537b31c369f985a6df9b3636dba7639ea7e628ea5aee003e10

It was reported by Robin in Discord/Core Tech, with the following details:
https://market.oceanprotocol.com/profile/0xc4a391C300987FDe197B2072f7837c5eEef2dcAC
https://discord.com/channels/612953348487905282/908016816029319178/993877582787383339

**Comment by kremalicious** [comment]
"No impermanent loss" was never communicated anywhere so not sure how this is listed here as expected behavior. The app UI always states that you provide liquidity into an AMM pool, which always incurs the risk of impermanent loss. Although greatly reduced in v4, it can still incur, just like in every other AMM.

**Comment by malvonme** [comment]
I know. I followed the structure recommended. I did not expect "no impermanent loss". That was the mindset / expectation. Just mirroring the community's reaction. Not on the core comms team. Was asked to write this ticket. 👍
