### ISSUE TITLE
Ocean Market UI Suggestions

### ISSUE THREAD

**Issue by jdune23** [oceanprotocol/market#160]
Ocean Market UI Suggestions

- Add rating system for publishers
- Add Comments section for dataset for buyers to review specific set
- Add Market/Buy section next to Publish on the top banner
- Add a browse section to search by specific theme, filter, etc...

**Comment by MattDeFi** [comment]
More UI suggestions:

- "Stickied" view of the pools you are staking in at the top.. as of now you have to remember which ones and search for them if they do not appear on the front page

- Ability to filter views of the data pools by data type, size, price, and liquidity

- When you click into a data pool, seeing specific liquidity statistics (i.e. X% growth/loss in liquidity over the past 12H,24H,1W)

- Purchase statistics for the data in similar terms as the above "liquidity statistics"

**Comment by MattDeFi** [comment]
Similarly, 

- Your own liquidity provider statistics per staked pool you'er in to understand how it is performing

**Comment by kremalicious** [comment]
good suggestions, thanks. just some quick notes: we are pretty sure that we will not add any functionality which would require a new centralized component like a database, which some of the suggestions imply. This pretty much rules out comments which we will not put on-chain ever. 

Ratings are actually part of the DDO and in the [dexfreight marketplace](https://dexfreight.oceanprotocol.com) we have built a blockchain-based ratings system around that, so that would be possible. But this would imply users have to send a transaction upon rating, meaning gas fees.

As for "Stickies", we start with some simple bookmarking right now https://github.com/oceanprotocol/market/pull/159

**Comment by MattDeFi** [comment]
Thanks for following up.

Makes total sense re: centralized database. Would that be required to also show liquidity statistics by pool (i.e. growth/reduction in liquidity over certain times)? It's tough to decipher if pools are growing or not at the moment which makes staking a bit riskier.

**Comment by kremalicious** [comment]
this is the whole big topic of market data for individual data sets and an overall market view of all combined, for which we explore multiple tech options right now.

The gist is that it is tricky since all statistics rely on blockchain events and querying that directly from the client app is expensive, which is why we created our own simple blockchain event indexer in-between (Aquarius), from which most of the UI gets its data, enhanced with live-fetching from chain in client app, like for the displayed prices. We will continue to add smaller features to Aquarius to show the most important data, but this usually only works out for info for individual datasets.

The fun starts with aggregated information, which already shows its limits when fetched directly from the client app, as you can see with the pool transactions list in your History. So we need a better solution for all of this, which is both performant and decentralized. The Graph, ChainLink, whatever fits for our very unique use case. Once we have that, we envision a separate information app like info.uniswap.org to aggregate all what's going on in all the datatokens & pools derived from our datatoken & pool factory contracts.

**Comment by kremalicious** [comment]
all of the mentioned suggestions were either shipped in some form, or are actively being worked on. So closing this issue for now
