### ISSUE TITLE
Support both datatoken templates when ordering an asset

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1652]
We need to support the other template as well for assets created outside the market. 
In order, instead of calling  `buyFromFreAndOrder` or `buyFromDispenserAndOrder` , we need to buy 1 dt from the fre/dispenser and the do the order. We can get the templateId from the subgraph.

**Comment by EnzoVezzaro** [comment]
Getting `templateId` (id) from subgraph:

<img width="346" alt="Screenshot 2022-10-04 at 05 35 23" src="https://user-images.githubusercontent.com/13741335/193786810-dc14ebdc-e263-4227-b550-02678f640ed6.png">

**Comment by trentmc** [comment]
The enterprise template was created for enterprise use, eg Daimler Market. Its features make things more closed by default.

Ocean Market is meant to be less gatekeeper-like.

I recommend that rather than supporting both an gatekeeper-like template (more closed) and the more open one, we only support one. The more open one.

**Comment by trentmc** [comment]
Given that "enterprise" doesn't actually mean for enterprises only, and its main gatekeeper-y thing right now in Ocean Market is that allowedswapper is not set to 0x00. If we just change it to 0x00, that's good enough for me, here. 

(And I still recommend not to support other templates in Ocean Market right now, there's bigger fish to fry: eg support eth-predict flows better.)

**Comment by kremalicious** [comment]
We have to support both. Do you want us to tell our users all existing assets can't be downloaded anymore?
