### ISSUE TITLE
deal with datatoken cap in publish flow

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#251]
In ocean.js the default cap when creating a datatoken is `1000` https://github.com/oceanprotocol/ocean.js/blob/main/src/datatokens/Datatokens.ts#L84

Which is not transparent to users. When users then want to mint more datatokens during create pricing flow, it will fail with `DataTokenTemplate: cap exceeded`.

Before solving this in a more holistic way on the contract level, we need an interim solution. Suggestions:

- in publish form, show the cap in the datatoken field
- optionally make it editable as text field
- needs a help text describing connection to minting in dynamic price creation

**Comment by trentmc** [comment]
[Better IDOs](https://github.com/oceanprotocol/multi-repo-issue/issues/36), a key part of V4, will implicitly handle this.

Because that's coming, I hesitate to do this issue beforehand, especially since it will raise many user Q's. That is, I recommend closing this ticket. @kremalicious is this ok with you? And cc @alexcos20

**Comment by trentmc** [comment]
As there was no pushback on closing this, I'm... closing it:)

Reopen if you feel otherwise.
