### ISSUE TITLE
Missing search bar in 'All data sets'

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#335]
If navigate to 'All data sets' you get the search page without the search bar. We should have an empty search bar, no need to hide it. If you want to search for something you need to go back to the homepage and then search.
![image](https://user-images.githubusercontent.com/26000280/105875832-f582ea80-6006-11eb-8e7e-61e0f0ed5b10.png)
![image](https://user-images.githubusercontent.com/26000280/105875855-fb78cb80-6006-11eb-96ae-a7364b86f6d5.png)

**Comment by kremalicious** [comment]
it was kinda intentional because of user intention. I know in the background we do a search but it's not a search to users, just a list of all assets. Likewise, those users on mobile should not see searchbar as the first thing, but the actual content, hence the searchbar was removed from the All Data Sets view

**Comment by mihaisc** [comment]
Well, looking at amazon or ebay the search bar is on the top on mobile and it makes sense. There is not much value to view all the assets and not be able to search

**Comment by jamiehewitt15** [comment]
I did a very small hack to make the search bar appear when the user clicks on "All Data Sets" https://github.com/oceanprotocol/market/pull/548

**Comment by kremalicious** [comment]
The better solution is a proper place for a search bar which user can invoke from any screen as described in #665, whereas #672 provides the needed space for adding this into the menubar
