### ISSUE TITLE
Error in buying data token while consuming file (step 2/3)

### ISSUE THREAD

**Issue by TSS-LauKY** [oceanprotocol/market#362]
**Describe the bug**
Error in buying data token while consuming file (step 2/3)

**Screenshots**
![image](https://user-images.githubusercontent.com/71874741/106695484-a8f66b00-6615-11eb-89a0-d77ebb973e59.png)

**Comment by kremalicious** [comment]
Any way to get what the browser console says? Did the transaction happen but failed when looking at Etherscan? What's the transaction hash?

**Comment by TSS-LauKY** [comment]
There is no error in the console.
![image](https://user-images.githubusercontent.com/71874741/106827875-32647680-66c4-11eb-9076-fb1b665419e8.png)

Asset:
https://market.oceanprotocol.com/asset/did:op:a36794Fba10eE5437F8c08ed0513FbCfd7a6D00D

Network:
Rinkeby

Transaction hash:
0x6a9b6d4b8365a4bbe6e4429fef59102a99d5595b09724223f9a7b8b288123c56

**Comment by mihaisc** [comment]
The timeout on this asset is 2 seconds, so basically you will most likely never be able to download it because by the time all the tx finish 2 seconds have passed so when you get to the download part the timeout has expired and you no longer have access and you need to buy it again. So you are in a loop.

**Comment by TSS-LauKY** [comment]
Thank for the finding. It's working after increase the timeout.
