### ISSUE TITLE
[Feature] Add Filter to display Most Popular Data Asset

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/market#365]
**Description of Feature:**
At this [page ](https://market.oceanprotocol.com/search?sort=liquidity&sortOrder=desc) on the filter tab, I suggest adding a sort by "Most Popular". 
![image](https://user-images.githubusercontent.com/39853992/106994978-d7607b80-67b8-11eb-97d8-45d7778b4fb7.png)
I believe this feature will be useful to show new user that are visiting the marketplace to observe what are the common most demanded data asset in the marketplace.

**Possible Solution/Approach:**
Perhaps adding another variable in the DDO metadata to store the total number of consumption for a data asset, then sort it using the graph query to display. 

I am not certain if is possible to auto increment the DDO metadata variable on each consumption on a particular data asset, because currently only the publisher of the data asset is able to republish the DDO metadata.

![image](https://user-images.githubusercontent.com/39853992/107001860-58be0b00-67c5-11eb-92c8-a7f824f05bca.png)

PS: Not sure if this would be a good approach, please correct/advice me if I am wrong.

**Comment by kremalicious** [comment]
yeah, all good ideas but we need to define `popular` first. In #355 we are aiming for a list of most visited page routes in last 30 days, so this would cover `popular` based on traffic.

Updating the metadata service is out of the question, this can only be done by the publisher account so no way for frontend to handle this. 

Another dimension of `popular` can also be all financial data around it, so volume and liquidity in the attached pool. But this would not be possible to combine it with the search, because all financial data needs to be queried with our subgraph and not from Aquarius which handles our search. From there we can also get the downloads for an asset.

So think best way to go about this is to handle this all on some `/usage` page as it is being looked into in #355

**Comment by soonjing** [comment]
Appreciate your insightful feedback @kremalicious

Lets say if we want to combine the financial data with the search (to do filtering in front end market), it would require the same method as attaching the price to the DDO outside of the services right? That is to do some customization on the Aquarius to query the chain.

For now, `popular` based on traffic should be the best option now 👍

**Comment by trentmc** [comment]
> For now, popular based on traffic should be the best option

I agree that we need to have a precise definition.

We need to get more specific yet, as even "traffic" can mean one of many signals:
* # times viewed
* # times bought
* # times staked
* # times consumed

Etc

My suggestion: consider supporting each of these signals, and use the precise label. 

The signal can be used in searching and filtering for sure. Could also consider it for the splash screen (browsing mode) too.

**Comment by mihaisc** [comment]
this will be handled here https://github.com/oceanprotocol/market/issues/661
