### ISSUE TITLE
UX issue: user can get stalled in Publish step due to surprising 'FILE' form behavior 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#366]
**Describe the bug**
In the Publish step, the 'submit' button is shaded-out / unclickable, and it isn't clear how to proceed to make it clickable.

**To Reproduce**
1. Go to market.oceanprotocol.com. 
2. Click button on top right to connect wallet (it can be rinkeby, mainnet, whatever). Make sure you have enough ETH.
3. Click on 'PUBLISH'
4. Fill out the whole form with test info. This includes: in the 'FILE' section, copy and paste, but do *not* hit Enter in the form or hit the gray 'ADD FILE' button.
5. Check the "I agree to these Terms and Conditions" box
6. Just below that box is the 'SUBMIT' button. But it's still shaded-out / unclickable. 
7. If I scroll up, there are no red warning labels next to any fields, good. Exception: there's a red 'REQUIRED' label next to the 'FILE' field, but that simply annoys me because I've already filled out the field. So I don't have any indication of what to do. So I feel stalled out, I don't know how to proceed. I fiddle with my wallet a bit, try a different browser, try a different os, nothing. (The way that it will go away is if I *do* click into the 'FILE' field then hit 'enter' or click the gray 'ADD FILE' button. But that is not obvious.)

**Expected behavior**

Best: For the 'FILE' text field act like all the other text fields in this form. There really shouldn't be a button 'ADD FILE', this should simply be auto-detected and verified.

OK: Or, (a) make it more obvious that the 'ADD FILE' text is actually a *button*. And b) if it's still not filled yet, the label should say more than just 'REQUIRED'; e.g. it should give an indicator of next step, such as 'REQUIRED, press ADD FILE button'.

**Screenshots**
Here's the perpetrator. Super frustrating. 
![file](https://user-images.githubusercontent.com/5305452/107144382-233b2e00-693b-11eb-81c9-9bdd9fa22df7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.x, Win 10
 - Browser: Chrome, Firefox

**Comment by kremalicious** [comment]
good points. Disabling the button by default was a workaround before proper live form validation was in place. Generally, disabling form submit buttons is a bad UX decision because users can't know the internal conditions under which button becomes enabled. 

A better pattern is to enable submit button by default and prevent form submissions based on internal live-validation (which we have implemented by now), and showing the errors in place where they happen. With that, a simple solution to presented issue would be to auto-scroll to respective file field on submit button click, and show a more helpful error message like `You need to add the file by clicking the button`.

A more user-friendly but also slightly surprising (to user) solution would be to auto-add the files when file text field is filled out but not added yet, and user hits form submit button. We could then in background check file through provider and get metadata automatically. Basically help user if they forgot. But surprising because metadata retrieval might fail, or URL is wrong, and user ends up with non-editable file metadata or wrong file. That was the main reason to put a hurdle in there so users can see in preview if file is alright.

Next room for improvement would be the file-adding component itself where we could figure out some other way to make it clear the file needs to be checked before adding. Cause we require user interaction here cause we can't detect when URL typing is really finished to auto-fetch in background.

And finally, the most holistic way of solving this would be a publish flow split up in multiple steps in a wizard where adding the file & sample is then on one screen and can't be continued unless files are added.

**Comment by jamiehewitt15** [comment]
I have implemented the "OK" solution in this pull request as a quick fix: https://github.com/oceanprotocol/market/pull/461

Changes proposed:
- Info text has been changed to explain that the "ADD FILE" button should be clicked
- Warning message has been changed to make clear that the "ADD FILE" button needs to be clicked
- Button styling has been changed to make it look more like an actual button
 
I think this could be merged in the interim while working on the "Best" solution

**Comment by jamiehewitt15** [comment]
I have updated the pull request so that the "ADD FILE" button is automatically pressed as an onBlur event. So as soon as the user moves to a different field in the form the dataset file is automatically validated. This implements the user experience described in the "Best" solution mentioned by @trentmc 

I haven't removed the button altogether as I thought there is no harm in keeping it there, users can still click it to verify their file. I could remove it though, as it is no longer necessary.
