### ISSUE TITLE
Market's price format is confusing

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/market#383]
Prices in the euro-zone (where I live) are generally formatted such that there's only two digits behind the comma. I think the same is true for the anglosphere.
Here an example from a German shop (license: https://creativecommons.org/licenses/by-sa/3.0/):

![image](https://user-images.githubusercontent.com/2758453/107969595-4192d080-6fb0-11eb-99a2-c2c8dbdd1f2c.png)

However, for some reason, on the ocean marketplace data sets are always shown having three digits after the comma.

<img width="360" alt="Screen Shot 2021-02-15 at 17 08 33" src="https://user-images.githubusercontent.com/2758453/107969735-71da6f00-6fb0-11eb-86a5-2ab6514b48dc.png">

As dots and commas are used differently in various languages, this makes interpreting the price difficult.
As a German e.g. I often get confused and think a data set is much more valuable than it is. E.g. the inital reaction to the data set above is: "oh is its liquidity now 67M OCEAN?".

To resolve the above-described issue, I recommend setting the maximum fraction digits of OCEAN value numbers to 2. Using `Intl.NumberFormat`, here's an example for en-US:

```js
new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(67642.916)}
"67,642.92"
```

**Comment by kremalicious** [comment]
Good German shop example, cause just think about how it would look like if the prices would be in BTC, then 2 decimals would not be enough to represent that fancy Minolta Image XT price in currently `BTC 0.00700119145724154`. Rounding it as `BTC 0.01` would be off by about EUR 200 right now. So this is an added challenge for formatting of crypto values, and we have to deal with multiple ones because of the conversion user choice.

For these reasons, the current implemented rules for number formatting are: 
- if it's fiat, use 2 decimal
- if it's crypto, use at least 3 decimals
- if it's crypto, show more digits when value is below 1

We simply use [coingecko/cryptoformat](https://github.com/coingecko/cryptoformat) for this, but oh boy is it inflexible and weird in some places, but so far it provided the best compromises to get consistent currency formatting no matter which currency and what value. It could make sense tweaking it further only for OCEAN display though

On top of that, the browser's `locale` is often not the actual regional preference, so international formatting is often not kicking in correctly either, and just defaulting to `en-US`. Or maybe `coingecko/cryptoformat` has a bug there too. Since we're kinda number heavy UI a dedicated number formatting preference might help as a shortcut.

**Comment by TimDaub** [comment]
Great reasoning. Thank you.
My two cents regarding the issue:

For any value that is denoted in OCEAN, for the time OCEAN < 100$, I think it's safe to display it with only 2 decimals as there's no information lost that is > 1 cent.

**Comment by kremalicious** [comment]
I fear this would be too hackish to only deal with OCEAN correlating to spot price throughout the UI. I would be in favor of rather ditching decimals above a certain number threshold for all currencies, say 1000, and numbers above that should always round up without any decimals. Since from 1000 on the thousand separators kick in, this would make the display less confusing already without any decimal separator.

Still would not consider this a bug, and not high priority but worth looking into if that's possible to do without forking the coingecko library

**Comment by TimDaub** [comment]
> Still would not consider this a bug, and not high priority but worth looking into if that's possible to do without forking the coingecko library

Sure. Actually, it may be worth giving it a shot over at coingecko. After all my last comment seems to remain valid. I'll try to give it a go soon...

**Comment by trentmc** [comment]
From a discussion with Alex, Matthias, Mihai: 
- your browser auto formats based on the region it detects that it's in (format that ends in decimals versus commas).
- as for three decimals versus two: it's a token, not a fiat. In the token world, the # decimals depends on the value of the token. 
- ultimately: we use the CoinGecko library as Matthias pointed out, that's a pretty good way to go. Therefore closing.
