### ISSUE TITLE
Liquidity graph isn't showing correct data when hovering with mouse

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/market#390]
System: Mac OS Catalina
Browser: 86.0b4 (64-bit)

When I go to a data set with high liquidity and hover over the liquidity graph I get multiple problems:

- The indicator in the graph (red dot) is not appropriately following my mouse cursor
- Somehow data recorded in November is shown on a much broader scale than e.g. data for Jan 2021 or Feb 2021

See .gif for example

![liquiditygraph](https://user-images.githubusercontent.com/2758453/108385403-ebba6480-720b-11eb-9f06-3aca97baa0d8.gif)

- I assume this problem also exists for the price graph. But I haven't tested that.

**Comment by kremalicious** [comment]
awesome, gif nicely captures the problem. The is due for an iteration since it was never tested with more and more historical data. Some small chart.js [interaction adjustments](https://www.chartjs.org/docs/latest/general/interactions/) might help already, or some data decimation before rendering the graph.

Ultimately, we should just copy interaction of whatever [Zerion](https://app.zerion.io/) is doing with their chart.js implementation, works just right as balance between info & minimalism:

![Screen Recording 2021-02-18 at 17 58 44](https://user-images.githubusercontent.com/90316/108392931-75b9fb80-7213-11eb-9c45-a4f4ffb3eaaf.gif)

**Comment by TimDaub** [comment]
Unfortunately many chart libraries in JS are bad. I've used https://dygraphs.com/ in the past. For lots of data points, it was performant.


> awesome, gif nicely captures the problem.

Glad I can help out.

**Comment by TimDaub** [comment]
@kremalicious I've started to use dygraph but I prefer a simple and lightweight library over all these huge ones. I've open-sourced [svg-line-graph](https://github.com/TimDaub/svg-line-chart/). It allows you to render a dependency-less and small `<svg>` with no additional features. It's still a WIP but maybe it's interesting to you guys. It should work both in the browser and on node.

**Comment by TimDaub** [comment]
>     * Somehow data recorded in November is shown on a much broader scale than e.g. data for Jan 2021 or Feb 2021

I think this issue was not addressed before closing this issue. Either that or the bug is now occurring again. See for LUMSTA-42 in FF from today:

![liquidity](https://user-images.githubusercontent.com/2758453/128727450-0b31b86b-611a-407d-b19a-0647fbe70671.gif)

Description: The scaling of the graph is skewed. From left to right, most data points are somehow between Nov 2020 and Jan 2021 and only a tiny portion is used to render the differences in 2021 (on the right).

**Comment by mihaisc** [comment]
That is normal behavior at this point since we are basing this graph on transaction history from the subgraph. So basically since in that period there were a lot of transactions we have a lot more data points there, thus a bigger chunk of the graph. I agree this is not ideal and might not be too intuitive. We have already started some work on the subgraph to improve this.

**Comment by TimDaub** [comment]
> That is normal behavior at this point since we are basing this graph on transaction history from the subgraph. So basically since in that period there were a lot of transactions we have a lot more data points there, thus a bigger chunk of the graph.

this is not "normal", it's wrong. E.g. for 2021, it takes a smaller fraction than 50% of the graph. It's completely misleading for anyone wanting to invest.

![Screenshot_20220117-195454](https://user-images.githubusercontent.com/2758453/149824446-9fec4314-f7c4-4282-9d45-28b3f76c3160.jpg)

**Comment by TimDaub** [comment]
for reference, the same graph in ocean with correct scaling of the axis and a smaller time frame (start jan 1 2021)

![Screenshot_20220117-200949](https://user-images.githubusercontent.com/2758453/149825767-39da46a4-6ca0-4640-9b97-0a9276dd3920.jpg)

**Comment by kremalicious** [comment]
might be solved magically with the new v4 subgraph's `poolSnapshots` (#1000) although we will never know for the old assets

**Comment by TimDaub** [comment]
> new v4

v4 that has been announced on the roadmap document for coming in Q2 2021... I can't wait for the Ocean Protocol team to break all of the ecosystem's applications with a selfish v4 update that could have simply been done by progressively shipping backward-compatible changes. Millions of USD have gone into developing apps with V3 and it's entirely unclear what's gonna happen in V4.
