### ISSUE TITLE
Marketplace performance, loading > 10 seconds

### ISSUE THREAD

**Issue by kaimeinke** [oceanprotocol/market#424]
Marketlplace is performing real slow, user complain that the screen keeps blank on mobile.

It just takes > 10 seconds to load right now.

![image](https://user-images.githubusercontent.com/59994024/110042139-9f137500-7d45-11eb-9339-94e5b895a305.png)

Sometimes it is faster or does not load at all ...

![image](https://user-images.githubusercontent.com/59994024/110042246-cc602300-7d45-11eb-9cb5-9041d18fded0.png)

**Comment by kaimeinke** [comment]
looks better now.

**Comment by kremalicious** [comment]
It looks like 2 different things happened at the same time:

1. the subgraph or Aquarius got really slow in their responses
2. a bug was introduced today (it was me in #421, sorry about that!), breaking the asset details view in browsers without a wallet

While 1. seems to have stabilized in the background, the fix for 2. is coming up in #425
