### ISSUE TITLE
Infrom users about alpha state of matic deployment

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/market#429]
@trentmc @mihaisc @kremalicious   - let's talk about possible messaging options

Reference: currently Ocean Market has 
- a "beta" tag
- a banner that says "We are in beta. Please familiarize yourself with the market, the risks, and the Terms of Use."

**Comment by trentmc** [comment]
I'll start with a stake-in-the-ground suggestion. Shoot this down all you like, but if you do, please provide a new suggestion! :)

Whenever Ocean Market is pointing to Matic, have a _second_ banner below the first, with slightly different color, that says:
"Matic EVM support is still in alpha"

**Comment by kremalicious** [comment]
please follow the discussion on the implementation https://github.com/oceanprotocol/market/pull/406

**Comment by trentmc** [comment]
> please follow the discussion on the implementation #406

Thanks. By that discussion I am guessing you mean this comment from you (Matthias) in particular:
https://github.com/oceanprotocol/market/pull/406#issuecomment-793726277

Here's a copy of that comment:

We will not find a simple UI pattern being able to convey to users what we mean by the beta/alpha distinction. We have to explain it anyway but at same time we actually want to encourage usage of that chain. So I would leave the beta label as is, and use the warning banner copy to convey what we think is the state of that chain. So when user switches to Matic, we have another sentence at top of existing message shortly explaining the state and most importantly link to the resources where we really explain it. That might be the launch blog post, or the various docs we prepared. If the layout shift caused by this paragraph is not enough to grab attention we could also switch the state to error then although that also comes over as a bit scary. In the copy we should NOT start with a beta/alpha distinction, nobody will understand [which part we mean](https://github.com/oceanprotocol/market/pull/406#issuecomment-791508249).

**Comment by mihaisc** [comment]
![image](https://user-images.githubusercontent.com/26000280/110467599-e2703980-80df-11eb-8e4c-09ccd05c6697.png)
