### ISSUE TITLE
Make chain/network part of asset URLs

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#431]
At the moment all asset URLs only work against ETH Mainnet assets, links to Rinkeby/Ropsten assets only work after user has connected wallet and pointed it to respective network. Inconvenience for users but fine so far because test networks. With #406 upcoming we need to solve this in a more generic way so it benefits all chain/network combinations.

### Proposal

Make chain & network metadata part of each asset's URL

```bash
# some ideas
/asset/eth/mainnet/did:op:xxxxxx/
/asset/did:op:xxxxxx/eth/mainnet/
/asset/did:op:xxxxxx?chain=eth&network=mainnet
/asset/did:op:xxxxxx?network=eth-mainnet
```

Query params are not so user friendly and look shitty as shared URLs, but probably easier from tech perspective.

#### Most simple use case

> URL of a data set in Matic mainnet is copied and shared, somebody clicks it and ends up on `market` without wallet and the asset should show up.

- on `AssetDetails` or component above, as soon as we have the route `path`, the chain/network provided in the URL becomes the source of truth to decide which network to connect to for this asset
- for the mapping we use our new ethereum-lists/chain helper which gives us `chain` & `network` for the URLs
- some indicator on each data set showing which network it belongs to, maybe only show it when asset !== default app configured network
- also need to nudge user to connect to the network of the asset for the actual actions to work
- migration path/redirects for existing Mainnet URLs, like auto-adding of network to URL when not present
- going all fancy, in case of 404 for a DID, we could check against all known Aquarius deployments in all networks until we find something

Tricky part to watch out for: user's wallet can then be connected to another network as the viewed asset which might need more work than just a UI indicator for it.

**Comment by trentmc** [comment]
I made this high priority due to polygon.

**Comment by TimDaub** [comment]
I just wanted to file an issue about the same thing. An OP user sent the following link to a data set on Polygone in Telegram: https://market.oceanprotocol.com/asset/did:op:6Fa2Ac3fb60235135e536db7475969Ad386B3d78

When trying to open it in my phone's browser, I get an error message that the data set hasn't been found.

About your proposal @kremalicious: I don't think it's the right approach. Let me quote the specifications from the respective [OEP](https://github.com/oceanprotocol/OEPs/blob/master/7/v0.3/README.md):

> Any kind of object registered in Ocean SHOULD have a DID allowing one to uniquely identify that object in the system

By allowing the marketplace to route a DID by itself, it becomes ambiguous and hence useless. Hence, I think the network part is vital to be included in the DID somehow.

I'm not a big fan of anticipating problems, but in this case I'll make an exception:

Say we proceed with the outlined proposal of attaching the network as a parameter in the URL and don't include it in the DID of the asset itself. This URL would allow linking to a specific asset:

`/asset/eth/mainnet/did:op:xxxxxx/`

1. It would mean that this URL would become an URI and hence be the real identifier of the asset
2. It would allow an attacker to issue a similar or equal DID on another network (e.g. using the CREATE2) op code.

I'm pretty sure the DID specification has a portion that addresses this exact problem. In fact, why not invoke the OG himself for advice: @msporny any ideas how to solve this?

**Comment by kremalicious** [comment]
this will solve itself and becomes redundant with what is currently developed in https://github.com/oceanprotocol/multi-repo-issue/issues/67, when one Aquarius instance indexes assets from multiple chains and the market shows them all.

And even right now we could go a more pragmatic route instead of making network part of asset URLs, dodging the rightfully laid out problems with that approach: on asset details view, app could query each known Aquarius endpoint until there is a match.

**Comment by TimDaub** [comment]
> And even right now we could go a more pragmatic route instead of making network part of asset URLs, dodging the rightfully laid out problems with that approach: on asset details view, app could query each known Aquarius endpoint until there is a match.

Given that two equal DIDs of two distinctly different creators could be resolved from different chains (as was outlined [here](https://github.com/oceanprotocol/OEPs/issues/232)), I don't understand how it can be possible to safely resolve a DID by iterating over the networks. In case someone created a fake asset on the first chain you iterated, you'd be showing the user the fake asset instead of the original asset. Besides, DIDs require global unique resolving, and that iterating over many networks increases the load of a resolver 2x already.

As a user of the OCEAN APIs, I'd prefer to know the location of an asset BEFORE I try to resolve it. From what I understand, this is what was your intention with creating this ticket too @kremalicious. E.g. when I just crawled the main chain, I just had to call as method once, now I'll have to call it twice without getting a guarantee about its validity anymore. What do you recommend I do now?

[I asked over at W3C](https://github.com/w3c/did-core/issues/715#issuecomment-803587169) and they told me that semantic versioning of DID-methods is possible, so that'd definitely an alternative if you want to avoid the above-stated problems in the future.

**Comment by alexcos20** [comment]
A DDO document is composed of standard DDO attributes:

@context
id
created
updated
publicKey
authentication
proof
verifiableCredential
dataToken
service

Until now, dataToken was a string, containing the deployed address of that datatoken contract.
What if, instead of being a string,  could be an array that looks like:
```
{
[ chainId: 0x1, dataToken: 0x12323],
[ chainId: 0x2, dataToken: 0x456]
}
```

This will help us in bridging assets between networks.  Same asset, with different bridged dataTokens

@trentmc  - thoughts ?

**Comment by trentmc** [comment]
> .. [ chainId: 0x1, dataToken: 0x12323] ..
> @trentmc - thoughts ?

Looks fine to me.

**Comment by alexcos20** [comment]
let's move to https://github.com/oceanprotocol/multi-repo-issue/issues/67
