### ISSUE TITLE
Check dataset connectivity on asset detail page

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/market#459]
When displaying the asset detail page, market should check if dataset is still available.

(ie: use [provider.fileInfo](https://github.com/oceanprotocol/ocean.js/blob/main/src/provider/Provider.ts#L136)

If files are not reachable, we should disable Download button

**Comment by kremalicious** [comment]
Yes, this sounds like a good solution for the actual problem behind #452.

Ideally we will not add more interval fetching on asset details for everybody since only a minority of users ending up there will ever click the download button so we should not have every user get the overhead of periodic pings. So I'm tending towards moving the ping to the place where it is actually needed, upon buying. So the first thing which should happen after user clicks Buy is the provider file ping. If it fails, drop out of process and show dedicated warning to user.

If we want that periodic checking for everyone, then we have to do multiple pings anyway, unless we want to ping every second. But I can see how this, with a small visual indicator beside/on the file icon, is a great way to signal trust in the dataset. But then we have to do the ping like so:

- on mount of consume/compute component (meaning switching between AssetActions tabs will refresh too)
- ping every 60s while mounted
- ping upon Buy click

**Comment by alexcos20** [comment]
I'm balancing between:
 - mount of consume/compute
 - check upon Buy/Download/StartCompute click

**Comment by mihaisc** [comment]
Agree with @alexcos20. No point in pinging at an interval, it's not common behavior to just wait on the details page for a lot of time. And if you do we check before you consume.
