### ISSUE TITLE
Algo list is not updating after editing compute settings

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#526]
After editing compute settings and clicking _Close_ in the final update metadata screen, the updates are not reflected in the `AssetSelection` in the _Use_ tab. Only a full page refresh updates them correctly.

### Expected

After updating compute settings and ending up back on asset details screen, the algo list reflects the just made changes.

**Comment by bogdanfazakas** [comment]
could not reproduce issue, maybe the ddo was not really updating in your test due to some back issues.
Tested the following flows updating just the publisher trusted algo list, changing to allow all published algo, then again allow just one algorithm, and the asset selection list was updated every time.

**Comment by kremalicious** [comment]
cool cool, tested again preview version of current state of `feature/compute` and could not reproduce either.
