### ISSUE TITLE
The Price of the dataset looks like the number of tokens in the pool

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#541]
**Is your feature request related to a problem? Please describe.**
On cards on the Market home page, where it says "488.88 OCEAN pool" - it looks like "488.88" is the number of tokens in the pool. 

![market pool](https://user-images.githubusercontent.com/20739535/115382368-4442b980-a1dd-11eb-89f4-66d552258153.png)

I feel like it should be made clearer that 488.88 is the price and not the amount in the pool. 

**Describe the solution you'd like**
I would suggest that we remove the word "pool" from here, I'm not sure it is needed directly after the price? 

To make it even clearer we could also add in the word "Price" directly before where it says "488.88 OCEAN"

**Comment by jamiehewitt15** [comment]
This issue of the price not being entirely clear has also been raised before slightly differently (with regard to the decimals): https://github.com/oceanprotocol/market/issues/383

I think adding the word "price" in would be a nice and simple way to make it clearer. I would also suggest removing the word "pool" from after the price - although purhaps there is a need to have it somewhere else on the card?

**Comment by mihaisc** [comment]
Didn't get any feedback related to this until now.  The confusion in that issue is not related to this, it's about the decimals and how we calculate tvl or liquidity how we call it (that is confusing indeed and we will rethink it) 
![image](https://user-images.githubusercontent.com/26000280/115387633-a0104100-a1e3-11eb-9d6b-a77e7c2a4d8a.png)
While i agree with you that it's not the best position for the `pool` tag, not sure if it make much sense to tackle it now. In the near future we will do a significant refactor and the price will disappear from there anyway. [This is a brief description](https://github.com/oceanprotocol/multi-repo-issue/issues/59#issuecomment-812436278), it needs some more thinking before actually starting it.

**Comment by jamiehewitt15** [comment]
Initially I was thinking of quite a simple change that would be quick to implement (like below) but I'm also happy to leave for the wider refactor as it sounds like this representation of the price will be obsolete soon.  

![price tag](https://user-images.githubusercontent.com/20739535/115890777-f7214a80-a45d-11eb-9931-c44155531e0b.png)

**Comment by mihaisc** [comment]
We'll leave it for the wider refactor
