### ISSUE TITLE
Unable to start a second compute job until the page is refreshed

### ISSUE THREAD

**Issue by DimitarSD** [oceanprotocol/market#583]
Once the user has purchased and started a compute job, he needs to refresh the page before selecting and starting a 2nd job (different or the same). Otherwise, he's going to receive an error.

**Steps to reproduce:**

1. Switch network to Polygon (not sure if it's network related, can't test right now on Rinkeby - TBA)
2. Go to [Daily Fishing Effort (01.01.2020) Dataset](https://market.oceanprotocol.com/asset/did:op:2f633467aD3e6d59c5235546752c4082F10672EF) and buy `Count data points (fixed price)` compute job
3. After the compute job has been successfully bought and started choose another one to start (`Count data points`) and click the button `START COMPUTE JOB`. You're going to receive `Error ordering assets`. Trying to run the same compute job will result in the same error until the user refreshes the page.
4. After page refresh the user can now start multiple (same or different) compute jobs

**Comment by bogdanfazakas** [comment]
Yeah it can be reproduced also on rinkeby, seems an issue with algorithm datatoken that you already own and trying to buy it again.
I can jump in and take a look at this

**Comment by DimitarSD** [comment]
Yep, go ahead. It might be related in some way to issue #569 (not sure yet) - I can't reproduce it on Polygon but I experienced the same behavior on Rinkeby. Although, with the current state of sync not sure what's really causing it.

**Comment by kremalicious** [comment]
Regardless of the flow changes we discussed yesterday, I think the mean issue here is that we simply do not do all the checks again right after compute job has been started which would imply the fix is to make some `useEffect` run again

**Comment by bogdanfazakas** [comment]
Yeap true, i have that also locally I'll push the draft pr for this immediately , so i trigger the checkPreviousOrder after the compute start for both assets in compute, but it seems to be also an issue with the graph on rinkeby at least, because i started a job with the following assets  https://market.oceanprotocol.com/asset/did:op:d5766cc73AE44977b4F7d72cDd3b33740101e830 and algorithm https://market.oceanprotocol.com/asset/did:op:aA16f337604cb5716995d30c23E92057ef2826Ef and the previous order from the graph are 27 April 2021 10:22:02 for the dataset and for the algorithm 22 April 2021 10:18:09 even if i have just ordered them today again and yesterday also. I'm still investigating that.
![Screenshot 2021-05-07 at 13 25 23](https://user-images.githubusercontent.com/13447142/117436561-c77f4180-af37-11eb-9abb-befe9d7b36d4.png)
