### ISSUE TITLE
More transparency to metadata history

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#770]
Given that publishers can change the title, description and even author of their dataset it would be helpful to provide an audit trail of when each of these fields has been changed. Currently, the metadata history shows when changes have been made but it does not indicate which fields were changed. 

It could be displayed on the asset detail page like below: 

![Metadata history - 2021-08-03_17-37](https://user-images.githubusercontent.com/20739535/128155140-b4790ef2-50f0-4960-abd3-4f3c96900b79.png)

**Comment by kremalicious** [comment]
This would be great, always imagined some kind of diff view for the metadata changes. Like, clicking on one edit opens a modal and you see additions/removals in a combined diff view.

All theoretically possible as metadata is on-chain. Practically not sure we can get this through the subgraph when we get the contract events for displaying metadata history items, so needs to be tested. Otherwise we have to think of something in Aquarius possibly

**Comment by mihaisc** [comment]
This is nice to have, but the effort at this point is way to big for it.

**Comment by srikanthkaja** [comment]
@jamiehewitt15 Is it something that is being worked on? Looks like a cool feature to have.

**Comment by mihaisc** [comment]
Something similar will be developed. You will have the same list of history items but when you click on an item you will be redirected to a page with the asset preview at that point in time. So you will be able to open multiple previews and compare them. There will be no automatic comparison.

**Comment by mihaisc** [comment]
Not sure when and if this will be done. When it's done in Aquarius we will reopen this.
