### ISSUE TITLE
Restore pool tab

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#971]
Restore functionality of the pool tab using the new subgraph schema

Do some add/remove/trade from 2-3 wallets (multiple people during pr review) for better testing.

Done:
-  you can view all the pool statistics without connecting a wallet . View own stats after connecting wallet

**Blocked by #954**

**Comment by kremalicious** [comment]
Mostly restored over in #993 meaning it renders and nothing crashes or produces console errors but some numbers seem to just `0` on the subgraph although they shouldn't be. So this issue here should become a double-checking issues where goal is to make sure all the numbers are actually making sense.
